### ISSUE TITLE
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io). My circuit hashes are as follows:

### ISSUE THREAD

**Issue by q446191796** [Unirep/trusted-setup#10]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: bc0f0a12b9974fb60cb8b830e5d587b509b4ad086ee093a3bd50a7bf408f4d1821d008b93a56196d1994e1c11a4e654ff17b99618a9882b18314be0607ccca76

**Comment by vimwitch** [comment]
related #1
