### ISSUE TITLE
[FE] Canvas and contributing page

### ISSUE THREAD

**Issue by ChialiT** [Unirep/trusted-setup#106]
<img width="682" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/eb87173c-5ba8-40d4-a461-e84919b11d79">

- the contributing page should be contain within a fixed width so it can render nicely on the larger screens, please refer to home page for the size.

<img width="687" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/53ca0399-0faf-470c-9017-7daae187cc34">
 
- Canvas instruction should be more obvious, increase the padding and simplify the instruction. it will be nice if we can add the border on the canvas.

**Comment by CJ-Rose** [comment]
- it should also have instruction that image can be zoomed and rotated; when i first looked i didn't know i could grab it and play with the angle.
- 'contribution completed' and 'share to twitter' elements should align over 'post as Gist' and 'contribution hashes' elements.
- canvas dimensions could be larger in height and smaller in width.

**Comment by ChialiT** [comment]
This issue was fixed, but i think it squeeze too much on large screen, this is what it produced
<img width="2698" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/94decc2d-432e-4df3-bd6c-3206ae0e8fa0">


@kittybest @CJ-Rose

**Comment by CJ-Rose** [comment]
@ChialiT fixed in #120
