### ISSUE TITLE
[FE] home page contribution list

### ISSUE THREAD

**Issue by ChialiT** [Unirep/trusted-setup#107]
<img width="831" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/2ba21551-0a03-486c-b6c2-a0cfb90447db">

contribution list should also apply the same width as the rest on the larger screen.

**Comment by CJ-Rose** [comment]
@ChialiT yeah,  i think maybe i didn't make my screen quite big enough to see it this way. no problem, i will constrain the table to the same width.
