### ISSUE TITLE
Gun

### ISSUE THREAD

**Issue by GunBacon** [Unirep/trusted-setup#11]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: 39a1e06b52131f19ee4c3b7ff4392b86ff226d7339e4f9fdbf7ccb39cc48fbf87b9eeec3e3c322c9ab711043fbd8614b8c3ad304cbcadc55825e66585a9a65a7

User State Transition: 56b18be1872cadcc8c5f7ddcc7f0a922c32d386e6a29314f41bf04802d94e1a596091984b76a18fd9f844437e7e0b08e435b6907ddeed09140727a30335f587a

Epoch Key Lite: 52a41e89b431c37d521ee8a8837d11fd34b15760476f29e65cfb75aa7e64561eba3cd1dffe5aa47e4de88c7d81ba55af32750a640789c7e638efee52ef882814

Epoch Key: b376f8923d40612258c9c58f7dde9994bb8fe64d8cd8361fc467b84f41ad16726f23a782001118188ff0ceb603ab9699f60475d5ec57ef11b0820741e36f99f0

Prove Reputation: 675cfe3135ef407313116c67edd6feb2dd65e4daf2a0b4d14f7aa1e635e2644c9deb3bccab6e72273e73feefc20137baf57baddaff258b81527ca1a0133fea1e

Double Action: e4dd3b7e46c52b68d77be08355b31ef34da57278c7cc522d7fbb5c3bbacd7a6b2face65a84b322e2373b860a77bb0d86a4b5c817167d3139393b7152f799a2a4

**Comment by vimwitch** [comment]
related #1
