### ISSUE TITLE
[FE] Request an Oauth token from Unirep organization

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/trusted-setup#116]
https://github.com/organizations/Unirep/settings/applications

Now it shows @kittybest 's username
It will be better to authorize through unirep organization

**Comment by kittybest** [comment]
how about twitter and discord? do we need to change all of them?

**Comment by vivianjeng** [comment]
If it is possible
I think twitter won't show your username (just the app name you set)
not sure about discord

**Comment by kittybest** [comment]
<img width="1315" alt="image" src="https://github.com/Unirep/trusted-setup/assets/9023842/bc2c49d4-05a8-4f73-941f-4e856610a001">

Just transferred, please check.
