### ISSUE TITLE
[frontend] Galaxy canvas is not responsive to window change

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/trusted-setup#118]
When I open chrome inspector and close it,
the galaxy is still in the size when I opened it

<img width="2373" alt="截圖 2023-10-05 上午10 17 58" src="https://github.com/Unirep/trusted-setup/assets/17507085/5d505218-38f5-4e38-91fa-2b0e4910d242">

**Comment by kittybest** [comment]
This is a problem we cannot solve, we mentioned at yesterday's meeting~~ (else the galaxy generation will keep starting from the start)
