### ISSUE TITLE
share

### ISSUE THREAD

**Issue by ciweiwen** [Unirep/trusted-setup#12]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: 1a6ea58425c28e69ed37115bb88f6beba10597882ccd86f923f41e269632354a9b3ed6bc0450bed15c23ffe3de3f450dbab22e58218f20cd94d25486c66c5d08

User State Transition: 2ebe77e08eb17a0e9123a34e3e99cbde51628092c945a990693b20002318e2b6b7ff4e345658c436f7afa4dcfb1bf2f4a1467e6b6ebd19fb3cff572a75cdabaf

Epoch Key Lite: 7333f138b0211985747e37c1ef4cc1a3bcb8c73821134036dba86910e5e5e97a5024a26860f851b07e09e1e3fe7f107b156e7b868a4d55d7a4d50dfd98772ac1

Epoch Key: 8f0dcb40ffbd9f0ec6e63d942ff74c12a7519d1767689db0a0e6c3502e49e950f425cf4552c48f150dff5fb5fad6ba13c80b2dafbee0788dc7b142a5c2b84fc2

Prove Reputation: 7ee3c0f5dd77463c5cc67246cf6974c3fa5e4331036a441d69847e758c08e3aa39a76b69fd39f9caff6b956b0658fef43a1cba95a311cad73da7332d5fc7b10b

Double Action: c3b4bec5b55406aba576965c92e2c09c5c2a6238165cc54d766292f13895a046e7658c9e7ba1934bb53898e2c07ffdbeeda4613d55bd9e122f8f79426e4cc087

**Comment by vimwitch** [comment]
related #1
