### ISSUE TITLE
[frontend] public attestations

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/trusted-setup#123]
there was a public attestations https://github.com/Unirep/trusted-setup/issues/1
should we change a new link?

https://github.com/Unirep/trusted-setup/blob/3e70f3d25730561e288067f8b2103659a1e426bf/packages/frontend/src/pages/Home.jsx#L190

**Comment by ChialiT** [comment]
> there was a public attestations #1 should we change a new link?
> 
> https://github.com/Unirep/trusted-setup/blob/3e70f3d25730561e288067f8b2103659a1e426bf/packages/frontend/src/pages/Home.jsx#L190

there is a link on stats page for all public attestation, previously was : https://github.com/Unirep/trusted-setup/issues/1
I'm not sure if we need it this way, it went a little too out of control previously.
what you think? @vivianjeng

**Comment by ChialiT** [comment]
let's remove the "public attestation" from stats page for now and same line of code that Vivi mentioned here.

will create another issue to view full detail of attestation

**Comment by vivianjeng** [comment]
yeah I think it can be removed
