### ISSUE TITLE
[FE] UI bug, feature bug before production

### ISSUE THREAD

**Issue by ChialiT** [Unirep/trusted-setup#128]
<img width="332" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/197b93d3-c008-4885-9963-affe7d1dcc1e">

- [x] Github auth. doesn't work, when user click on github aut. it produce this error

<img width="3355" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/45835277-fc08-4e34-b30d-5ba6503982a1">

- [x]  on large screen, this UI doesn't make design. it should have 2 columns.

<img width="595" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/d5153878-f4f3-4121-8eaf-46d79f06fab0">

- nice to have

- [x] we should have the meta description for the URL.

<img width="934" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/7ee78a97-f674-453f-b61d-ca1d4cbf91b9">
- Gist

- [x] it should write "I just contributed to the UniRep trusted setup ceremony." (remove the "dev" and casing for UniRep)

<img width="816" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/a538847f-0fcb-4839-937f-1fc673d52bc4">

- [x] back to top btn doesn't work

**Comment by kittybest** [comment]
Github/Discord oauth-ing bug: https://github.com/Unirep/trusted-setup/pull/129
