### ISSUE TITLE
1

### ISSUE THREAD

**Issue by wangyanfei0128** [Unirep/trusted-setup#13]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: b9c1d630e0765705a80342b2499281a4229943141d0505b0570e0c0245bd88d6389ae9be8f017ff2b955084bf30fbc1f48ad6894e0f7c5e5597048509971858d

User State Transition: 2c599e343f3ef8330a72a4e134b0b44f2ebbbd1b69fafded51d554133db9a6430b6aa052af3411eda9f174e7262c448996a25e5fe920435c533162533b5199e9

Epoch Key Lite: cfdd124cdf166241b5df76eed9f042af1d3eb35dae639bdf0c50da802cb081fdfd4ca68f7aea83eab1854918f4476bb201a54fc9943e2b0094eb13bf94ee6ca6

Epoch Key: 513162979ba65974efd01edb426d7f3924517c2292e5d42fb9c1df4f7c638e0bd75f9e2db9345a08132c1883b7cbf036caab1c31e415347f8a7a3a840ba5b3f5

**Comment by vimwitch** [comment]
related #1
