### ISSUE TITLE
[FE] Home page contribution list bug

### ISSUE THREAD

**Issue by ChialiT** [Unirep/trusted-setup#135]
<img width="1217" alt="image" src="https://github.com/Unirep/trusted-setup/assets/16527634/ffa3d67c-0f74-4f41-84b9-87c3555a97f2">

there seems repeated info, we will fix this along with the other issue to allow user view more detail via a popup

**Comment by CJ-Rose** [comment]
@ChialiT did you contribute twice? i see your name x2 on each circuit on Stats page contribution table.
i think the repeats on home page table are bc we didn't separate them by circuit, we are just pulling the most recent 5 so they will usually be 5 of the 6 circuits from the same person.

**Comment by ChialiT** [comment]
> @ChialiT did you contribute twice? i see your name x2 on each circuit on Stats page contribution table. i think the repeats on home page table are bc we didn't separate them by circuit, we are just pulling the most recent 5 so they will usually be 5 of the 6 circuits from the same person.

i think I did contribute twice by accident. but we can see the index number is repeating on the home page tho

**Comment by CJ-Rose** [comment]
> think I did contribute twice by accident. but we can see the index number is repeating on the home page tho

yeah, i think bc those contributions were made at the same index # in each circuit's separate list

**Comment by vivianjeng** [comment]
https://github.com/Unirep/ceremony/pull/2
