### ISSUE TITLE
1

### ISSUE THREAD

**Issue by kunkun073** [Unirep/trusted-setup#15]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: 23092e58ed7e6d4a7a9e06012643a8d97d869ec0ee4189ed6f56882815a25eba607c6706ba15f0040d155be04c5c540bfcd42cb38450b6cb7c4beb5ed0d69603

User State Transition: 499155e8bf984a387b48ea54863bea9856336b3e9dd99e594defddea5bf24f63e816c12a3b4090cc04de003d58d8963cfa253202e01b5c02c38bc6dd06108969

Epoch Key Lite: 7b223964a61e1c7f7358cfe3f961585f4f9f96b7e8bf0f5bbe3ab263ce2b4c6f41c00b3f0e3662ba1888fe35ce069f588d7c85b8adf1d9b1b6f6d776a3acebb8

Epoch Key: 480a2fef336dc5452d5b2e8b44e1faf562c99f5177259869810869b7502ad4782287f5c0daea67d76728fdf27a861525ffa7eb983e9975a1fe00c81f7009d18f

**Comment by vimwitch** [comment]
related #1
