### ISSUE TITLE
dev.trusted

### ISSUE THREAD

**Issue by phfbs517** [Unirep/trusted-setup#2]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: 54a32fd4ec4af2bfa50cd76a2f856d0fbbfeaef0b47391101d89eada6dfc18995ac4c1a0ae5f2c94df71bc4ffd25161d1052295c5b4e2558925d0c4a39c2121b

User State Transition: bd7201e7403641eb12a0d39fafecab523e48b2d1d96f1d21d74370409a897bdd807a250ff10911db0e2ce083e9e516bdf28bf6c7e2e1a0f83e445cec5a6cfa07

Epoch Key Lite: 3c5ce2b5059b3d0ee0dacb60b933d84ddbad567ebe786fa4bca5bb7f192be3559199f299685ec15f48cc6e05f63cb7ca5c1f727f9dd6e9feb01983a08992c98b

Epoch Key: a19d145e544eed94597513198016bef1d3ebe2639a53ce97e652b8f0b9032b9686ea570057bf6af6d46e5429e205f159b120649967ca83f253b9a2fa5d70b126

Prove Reputation: 483e3280a39d77d3e12900b0564a7bc076e80e02867b7f8c4d459465baf2a55279566ce250fccb1768b99266faa52bcd447fee33cbc4cef4f6c2ca5dd1f94950

Double Action: fddafa322c0af0d062ac6c857c501c0f657728f0ad20ca9fcbbb0b93b81458ceffe570558a0261ffdd0929b82de1ed0b6f4a9e499f7f88da853c5f1a53facd45

**Comment by vimwitch** [comment]
related #1
