### ISSUE TITLE
evan van ness

### ISSUE THREAD

**Issue by dinahjohn11** [Unirep/trusted-setup#3]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: 7258cbf369011129f94fa15a2064137d66df37c450e184678af95d9d8bb010a3bb7bdadeca7ec7b6df88908b42fa70480fe76845af574b154c4cdf037467649a

User State Transition: 6411c5772cec6cb8ec634d90e0c48002cc5d1bb43caf9ae56642a3267b8a6e699cf61b1ba1fbc7ebbe0538a667a9d9beb66f6091409bd14e6a9155d9d7aa135d

Epoch Key Lite: a9eefff88a1064b9d1df20986e790462d1623c1b9aa2c491d174b2dfa6d95f991ff3c55c99ef35e1440d7a6aa0c49761817bba56aec60a3170ff80fb22485a6a

Epoch Key: a3f34b33e95c0c8804d97998f26327a50cad8e77576735738f5b0ca06689abe8a215cb4cc1e407f1019a4be9f1141c84649ab583ea29265b5895ce22b1332c1b

Prove Reputation: 963dd15633db82c4b64e6d736d9cb8d3ed571c13d3a8b007ca9b33dc922d3ea64e1f8977e0726fd0454849250c9506f2055e46f2ebd273a140545528325dc0b0

Double Action: 0b0e76f7bdde9aa310a5da4e115fc75f20ade95f9d93b734cc223bb34a5007c406e25825b4ec3880b4e1a05a20de2b70d7a5fc6ae8ec9988162612af24e6600a

**Comment by vimwitch** [comment]
related #1
