### ISSUE TITLE
evan van ness

### ISSUE THREAD

**Issue by goodehadley5** [Unirep/trusted-setup#4]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: 6c7a6c8477a4938006a1e2b3d33ea253fb1d2b366108336ae3a782c95fb67fc91a98654c19ae63a55aadc5e11162b7fdc4702237d6aeccb83ae83f0d79849eca

User State Transition: bacc8ee9505ebda14a61283c6ca91c7121b111ed14386f48f23377af45bc5f1f41f65ebcdc7b5520bac1fda71cb412b23737fe3364d21e354c86710f80fb6d8f

Epoch Key Lite: e05dd45b74cb34fe2d7ca380e8bfcf867f4412624fcc98f168b098e5496fd2ceed73d7304bf5df2d15b539ffb89239dfc6965eabf67784013f0a2793e721c633

Epoch Key: 4882bc8b7ce4b7bab561bd2720d84ceacab580c006327b569e9ca2fd28a600a202040d9b90acd15167d739d4fe89ab3b36753fdc208fa32ccfe77f5ffd70b755

Prove Reputation: bc75ec9cdf87713511c872ce27fb879036a860b95671cabc1470be7e36ae7cb637f939a2c26faffb973c54981816f6ab9e0cc0dd0a2b762b3a47fd7950be53e4

Double Action: d79820d703f4e5bfac0063ddde6a1b8abfb33fa025e187edd1b11ffae19c94d2cdeef5b89802a2d4653e031f7a370e0a0824c899380843aed5e29990904afe8b

**Comment by vimwitch** [comment]
related #1
