### ISSUE TITLE
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io)

### ISSUE THREAD

**Issue by guochaozhang678** [Unirep/trusted-setup#6]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: c118bc6532960127912c8ca413aa1af44ce2a84277c4776a7306ce3533e3725713f0f0895c95d98641a1beafd16d8c87f27be0da6fb0fe37b3de95887d45479b

User State Transition: 6b530938923b90210c7aae148b25fd74185b449780bb787a863115853213ee8b67ebd2d4fd904c27335b38208f395852c0d0e1cbe4f312f98e7137914f717748

Epoch Key Lite: 5bb6286fe6fba9e53b40c77496355c349247806ec6e019979ae17864246c6172f3c8479509b3e2ee1f8c6efeef8b5f366222fa08c4dbd863cd3085c429d381da

Epoch Key: 998cd60803d496726d04565d3c0c30a8fb6c053161e8fe8bfc828c50a039ced9a2503aeaeff901fe9d1c97b576ee2516b5784de41400b46d14ccf36cd1e1fa95

Prove Reputation: 1bc60ddff207a415522cc73131bb0e33f8bbd94160e24ec476c2556f01c2c02f5f85261e22c74aa46a65dbed44a70fc7ca1de64966addbba9a22ce1261aeedcc

Double Action: f4499d91ab6a481acf425e24320ee7072f95e1a60f96f9726baed4cd2757e01e97d04769a9b6285dfcaf00d3072e2182ccccbbe179d0f4e39b9dbd0d70b04a28

**Comment by vimwitch** [comment]
related #1
