### ISSUE TITLE
1

### ISSUE THREAD

**Issue by bdfgsdf** [Unirep/trusted-setup#7]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io/).
My circuit hashes are as follows:

Sign Up: 231fe7f198855e03cc53f24d0d58c5b1e10d20a996a2742d2fbae62132a60713302b261a67463a236d1a14e05c896f4bdd5d93380136707181a37339704fead7

User State Transition: d7ca74989d5ac188a75715e4adad3f6b116c689e2345b6d2b5b9f537d27424a14d451790ba652dd91872855a8535e9cf0bd24ff65d6991f9f197f43dd4f8ef60

Epoch Key Lite: d7063919ddda50fb6ba58ba3d62a1a32bd36141d41fe18ce451b207d32d60b52aec3a526fc9cb89ffb3c13957e07fb0cee372f7becc55a17e776600832a0db04

Epoch Key: 974075bfeea79357083c85af0591ddbb0f8b67ec481ca871efb0fccf43262d5bc6125a9a3c39f10ff4ebcc9dfac9ffe7c6f391fb20b126d700429dda7fb20e37

Prove Reputation: 1291485c6e48718b00ba33617c7e939929110cf95fdbff0db041e58900fedf4a6d43c8bf0105540cfc7f8f606a4bfcb6d401389fbd57b544b42cc73d0dc874e0

Double Action: c151f5e546982477b150a78dce80edc7ac66a24617d106e52516e886f31c3990e1bdfeb854beb4e77aac1db80d7e50e666349ba023e1a7b542df1fed9466b65d

**Comment by vimwitch** [comment]
related #1
