### ISSUE TITLE
LFG

### ISSUE THREAD

**Issue by wuytiuo11** [Unirep/trusted-setup#8]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: fb85f128f2813e7287454ae2d8c576e9ccfcbd1e8896d1634e1d871f50130a10d6dc4ed5d18373fb7d86bf95a43cf81ddb8ec067442dac08418b6b55440535d7

User State Transition: d19b27fa480d811ddb59972ba760ef6fcca6630c4093a7fad36e3a5b2a0187bebfc2497684ecdf5da35e1de511100a1e8e9b4be6c7e52f8503471701f7d3482c

Epoch Key Lite: 3a982608799b0b27912bc89083dc4ce91f6286d1392bbe221a8e816446b55f8290c89bc0f8a7f701c132811343f0f060521572f6c2003b5e20b7b0bb5156d376

Epoch Key: 2b7a6432bc23cbfb795092eea49594c6d518549c2f521df8066a07c001acad7b227503913363c6f94ea338aafde9026a7133d0618505a794e516d467c9d34995

**Comment by vimwitch** [comment]
related #1
