### ISSUE TITLE
z

### ISSUE THREAD

**Issue by ldcsd** [Unirep/trusted-setup#9]
I just contributed to the unirep dev trusted setup ceremony. You can too [here](https://dev.trusted-setup.unirep.io).
My circuit hashes are as follows:

Sign Up: ab601a952b7d69d502d6cc2afbe95c1f25014ffac5b2846e7e119c9d00b6cf359145d920a6e6bb875e2570cfee51e949d6d171f88d4ef4b0b0591fe63d570e51

User State Transition: 8b56d234f210e2fb9d73c3be033ee6c5ef78b65d8ee558bf0d0155d54c70653c75a03fa5db13b203dd389e8562f3d0654f48c98fa5c6ac4b0438d46b685badb1

Epoch Key Lite: 08a8b019e225f2493733030d46ff0c8e7bbf8bd5d18d8d5c077b2c733c5d77109b918a8d6193df844d520eda2128e5ddaa8228d52031fa7c9148c1eee5c38ce0

Epoch Key: 2b224ce3a79138c1c39b61630624c5a21c3c6dadad1e22b3e82750cccfb2ac8f078496653ee4378f19843e2730aee648ff30b7b788d91414ceef563abfa18fb6

Prove Reputation: 1c4244f4abbf4f07dc6f57309663417049900dd7e4bb53d64f863949ac1ea4288e2b340db188287987eabd12eb05353db11418d902cc7773fff57c55fa5b03d5

Double Action: 40092896ef6510020f22d887b64e1e68966fa71171ea11b501c4848a7a39ff05070517c2f857fa669536bb9c0c5b68cf937220fa39f06847b7dc13905a64ef52

**Comment by vimwitch** [comment]
related #1
